// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'addErrorAlert': string;
  'importButtonIcon': string;
  'rootFoldersSection': string;
  'sectionHeading': string;
  'tipsBlock': string;
  'tipsIntro': string;
  'tipsList': string;
}
export const cssExports: CssExports;
export default cssExports;
