// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'error': string;
  'meta': string;
  'metaLabel': string;
  'metaValue': string;
  'previews': string;
  'selectAllInput': string;
  'selectionGroup': string;
  'selectionLabel': string;
}
export const cssExports: CssExports;
export default cssExports;
