// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'added': string;
  'addedSegment': string;
  'gutter': string;
  'line': string;
  'lines': string;
  'removed': string;
  'removedSegment': string;
  'row': string;
  'selectedContainer': string;
}
export const cssExports: CssExports;
export default cssExports;
