// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'buttons': string;
  'error': string;
  'field': string;
  'fieldLabel': string;
  'footer': string;
  'label': string;
  'section': string;
  'sectionHeading': string;
}
export const cssExports: CssExports;
export default cssExports;
