declare const styles: {
  readonly "actions": string;
  readonly "added": string;
  readonly "averageSizePerEpisode": string;
  readonly "banner": string;
  readonly "bannerGrow": string;
  readonly "certification": string;
  readonly "episodeCount": string;
  readonly "episodeFileQualities": string;
  readonly "episodeProgress": string;
  readonly "genres": string;
  readonly "latestSeason": string;
  readonly "monitorNewItems": string;
  readonly "network": string;
  readonly "nextAiring": string;
  readonly "originalCountry": string;
  readonly "originalLanguage": string;
  readonly "path": string;
  readonly "previousAiring": string;
  readonly "qualityProfileId": string;
  readonly "ratings": string;
  readonly "releaseGroups": string;
  readonly "releaseTypes": string;
  readonly "seasonCount": string;
  readonly "seasonFolder": string;
  readonly "seriesType": string;
  readonly "sizeOnDisk": string;
  readonly "sortTitle": string;
  readonly "sorted": string;
  readonly "status": string;
  readonly "tags": string;
  readonly "useSceneNumbering": string;
  readonly "year": string;
};
export = styles;

