// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'emptyLabel': string;
  'icon': string;
  'iconUnavailable': string;
  'path': string;
  'pathUnavailable': string;
  'row': string;
  'stats': string;
  'unavailable': string;
  'unavailableLabel': string;
}
export const cssExports: CssExports;
export default cssExports;
