// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bordered': string;
  'intro': string;
}
export const cssExports: CssExports;
export default cssExports;
