// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'error': string;
  'languageCheckContainer': string;
  'languageName': string;
  'languageRow': string;
}
export const cssExports: CssExports;
export default cssExports;
