// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'error': string;
  'intro': string;
  'languageInput': string;
}
export const cssExports: CssExports;
export default cssExports;
