// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'action': string;
  'cause': string;
  'content': string;
  'cover': string;
  'coverPlaceholder': string;
  'dot': string;
  'dotHealthy': string;
  'dotWarn': string;
  'list': string;
  'row': string;
  'section': string;
  'sectionHead': string;
  'sectionMeta': string;
  'sectionTitle': string;
  'serif': string;
  'title': string;
  'titleHealthy': string;
}
export const cssExports: CssExports;
export default cssExports;
