// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'courBreak': string;
  'dot': string;
  'is_airing': string;
  'is_future': string;
  'is_grabbing': string;
  'is_missing': string;
  'is_owned': string;
  'pulse': string;
  'strip': string;
}
export const cssExports: CssExports;
export default cssExports;
