// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'content': string;
  'cover': string;
  'coverPlaceholder': string;
  'ep': string;
  'epCode': string;
  'list': string;
  'release': string;
  'row': string;
  'section': string;
  'sectionHead': string;
  'sectionMeta': string;
  'sectionTitle': string;
  'serif': string;
  'show': string;
  'time': string;
  'viewAll': string;
}
export const cssExports: CssExports;
export default cssExports;
